name: TestPlugin
version: 1.0-SNAPSHOT
main: com.example.project.testPlugin.TestPlugin
api-version: '1.21'
authors: [ Hadwwikk ]
description: My first plugin
commands:
  event:
    description: Main event command
    usage: /event <start|info|location>
permissions:
  event.use:
    description: "Allows using the /event start command"
    default: op